import base64
import json
import os
import re
import sys
import time
from openai import OpenAI
from PIL import Image
from io import BytesIO
from datasets import load_dataset
import random
from agenttools import BaseTool, ToolUsageExample

# --- Configuration ---
# IMPORTANT: Replace with your actual API Key to run the code.
API_KEY = os.environ.get("LAMDA_API_KEY")
API_BASE = "https://api.lambda.ai/v1"
MODEL = "llama-4-maverick-17b-128e-instruct-fp8"

from agenttools import BaseTool, ToolUsageExample # Add these imports

# --- Main ScienceQATool Class ---
class ScienceQATool(BaseTool):
    def __init__(self, api_key=None, api_base=None, model=None):
        # --- FIX IS HERE ---
        # 1. Initialize the parent class with only the 'name' argument.
        super().__init__("scienceqa") 
        # 2. Set the description as an attribute of this class.
        self.description = "A tool for answering science questions that may include images, diagrams, and text."
        # --- END FIX ---
        
        self.api_key = api_key or os.environ.get("LAMDA_API_KEY")
        self.api_base = api_base or "https://api.lambda.ai/v1"
        self.model = model or "llama-4-maverick-17b-128e-instruct-fp8"
        
        if not self.api_key:
            raise ValueError("API key is missing for ScienceQATool.")

        self.client = OpenAI(api_key=self.api_key, base_url=self.api_base)
        self.preprocessor = ImagePreprocessor()
        self.vlm_engine = VLMAnalysisEngine(self.client, self.model)

    def run(self, data_item: dict, dynamic_prompt: str = None) -> ToolUsageExample:
        """
        Processes a ScienceQA data item using a dynamic prompt from the agent.
        """
        print(f"🔎 Querying ScienceQA Tool with context...")

        image_uri = self.preprocessor.process(data_item.get("image"))
        if not image_uri:
            return ToolUsageExample(tool_name=self.name, user_query=data_item.get('question'), llm_response="Image processing failed.")

        # The VLM engine handles the core analysis
        vlm_result = self.vlm_engine.analyze(
            image_uri,
            data_item.get("question"),
            data_item.get("choices"),
            data_item.get("lecture")
        )

        final_response = f"""
==================================================
✅ Final Answer Generated by ScienceQATool:
==================================================
{json.dumps(vlm_result, indent=2)}
==================================================
        """
        return ToolUsageExample(
            tool_name=self.name,
            user_query=data_item.get('question'),
            raw_prompt=dynamic_prompt,
            llm_response=final_response,
            parsed_output=vlm_result
        )

# --- Tool 1: Compendium Generator (Revised) ---
class CompendiumGenerator:
    """
    Analyzes a slice of the dataset to generate a single, structured JSON compendium
    based on a predefined, detailed template.
    """
    def __init__(self, client: OpenAI):
        self.client = client
        print("Tool Initialized: CompendiumGenerator")

    def generate(self, data_slice: list) -> dict:
        """
        Generates a single compendium by instructing an LLM to populate a detailed
        JSON structure with multiple usage scenarios derived from the data.
        """
        print("\n[Compendium Gen] Starting single compendium generation...")
        print(f"[Compendium Gen] Analyzing {len(data_slice)} data items to build context...")

        # Create a rich sample of questions for the LLM prompt, ensuring variety
        examples_for_prompt = []
        processed_questions = set()
        # Shuffle the data slice to get a more diverse sample
        random.shuffle(data_slice)
        for item in data_slice:
            if len(examples_for_prompt) >= 30: # Increased sample size for better context
                break
            question_text = item.get('question')
            if question_text and question_text not in processed_questions:
                examples_for_prompt.append({
                    "topic": item.get('topic', 'N/A'),
                    "question": question_text,
                    "skills": item.get('skills', [])
                })
                processed_questions.add(question_text)

        examples_str = json.dumps(examples_for_prompt, indent=2)

        print("[Compendium Gen] Sending detailed sample to LLM to populate the compendium structure...")

        # The exact structure provided by the user is now the template for the LLM
        compendium_format_template = """
        {
            "Textual_Compendium": {
                "Tool_Description": "A comprehensive scientific reasoning suite designed to interpret visual and textual data across various scientific domains.",
                "Usage_Scenarios": [
                    {"scenario": "Physics: Force and Motion Analyzer", "context": "Analyzes diagrams related to forces, friction, motion, and energy to solve physics problems."},
                    {"scenario": "Biology: Ecosystem Interpreter", "context": "Interprets biological diagrams like food webs, cell structures, and life cycles to answer questions about organism interactions."},
                    {"scenario": "Chemistry: Molecular Structure Analyst", "context": "Parses chemical diagrams and formulas to answer questions about reactions and properties."},
                    {"scenario": "Earth Science: Geological Map Reader", "context": "Reads geological maps and charts to understand earth processes and history."},
                    {"scenario": "General Science: Data Chart Interpreter", "context": "Parses bar charts, line graphs, and tables to extract trends, make comparisons, and answer data-driven questions."}
                ],
                "Precautions": [
                    {"precaution": "Image Clarity and Labeling", "details": "Performance heavily depends on the clarity and correct labeling of diagrams and charts in the provided image."},
                    {"precaution": "Complex Multi-Step Reasoning", "details": "Questions requiring extensive multi-step logical deduction may challenge the tool's reasoning capabilities."},
                    {"precaution": "Implicit Knowledge Requirement", "details": "The tool relies on its training data and may not have the specific, niche knowledge required for highly specialized topics."}
                ],
                "Multi_tool_Coordination": {
                    "Description": "The system orchestrates a pipeline of specialized tools: ImagePreprocessor -> VLMAnalysisEngine -> ExplanationSynthesizer, guided by this compendium.",
                    "Examples": [{"example": "For a chart-based question, the system first preprocesses the image, then the VLM extracts key data points, and the Synthesizer uses the 'Data Chart Interpreter' context from the compendium to frame the explanation."}]
                }
            },
            "Structured_Annex": {
                "Entities": ["Science_Problem", "Visual_Diagram", "VLM_Analyzer", "Final_Explanation", "Scientific_Domain_Tool", "Data_Chart", "Chemical_Formula"],
                "Relations": [
                    {"source": "VLM_Analyzer", "link": "analyzes", "target": "Visual_Diagram"},
                    {"source": "Scientific_Domain_Tool", "link": "guides", "target": "Final_Explanation"},
                    {"source": "VLM_Analyzer", "link": "interprets", "target": "Data_Chart"},
                    {"source": "Scientific_Domain_Tool", "link": "specializes_in", "target": "Science_Problem"}
                ]
            }
        }
        """

        prompt = f"""
        You are a system architect designing a single, comprehensive compendium for an intelligent tool that solves science questions.
        Your task is to analyze the following sample of ScienceQA questions and use them to populate a detailed JSON compendium.
        Infer at least 5 distinct problem-solving domains from the sample data and create a detailed 'Usage_Scenarios' entry for each.
        The 'Tool_Description', 'Precautions', and other fields should be written to reflect a versatile science-focused system.
        Your entire response must be ONLY a single, valid JSON object that strictly follows the provided structure. Do not add any text before or after the JSON object.

        **Sample Questions Data:**
        {examples_str}

        **Required JSON Structure (fill this out based on the data):**
        {compendium_format_template}
        """

        try:
            response = self.client.chat.completions.create(
                model=MODEL,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=3072, # Increased max_tokens for a larger, single JSON object
                temperature=0.4,
            )
            response_content = response.choices[0].message.content
            # Clean up the response to find the JSON object
            json_match = re.search(r'\{.*\}', response_content, re.DOTALL)
            if json_match:
                json_str = json_match.group(0)
                compendium = json.loads(json_str)
                print("[Compendium Gen] Successfully generated the consolidated compendium.")
                return compendium
            else:
                raise ValueError("No JSON object found in the LLM response for the compendium.")
        except Exception as e:
            print(f"[Compendium Gen] Error generating compendium: {e}")
            return {}


# --- Tool 2: Image Preprocessing ---
class ImagePreprocessor:
    def process(self, image_input):
        if not image_input or not isinstance(image_input, str): return None
        try:
            # Clean up the base64 string header if it exists
            if "base64," in image_input:
                image_input = image_input.split('base64,')[1]
            img_data = base64.b64decode(image_input)
            img = Image.open(BytesIO(img_data))
            with img.convert('RGB') as rgb_img:
                buffered = BytesIO()
                rgb_img.save(buffered, format="JPEG")
                base64_string = base64.b64encode(buffered.getvalue()).decode('utf-8')
                return f"data:image/jpeg;base64,{base64_string}"
        except Exception as e:
            print(f"❌ Image preprocessing error: {e}")
            return None

class VLMAnalysisEngine:
    def __init__(self, client: OpenAI, model: str):
        self.client = client
        self.model = model

    def analyze(self, image_uri, question, choices, lecture):
        prompt = f"""
        You are an expert scientific analyst. Analyze the provided image and text to answer the multiple-choice question.
        Your entire response must be ONLY a single JSON object with two keys:
        1. "reasoning": A concise, one-sentence explanation for your choice.
        2. "answer_index": The integer index of the correct choice.

        **Contextual Lecture:**
        {lecture}

        **Question:**
        "{question}"

        **Choices:**
        {json.dumps(choices)}
        """
        message = {
            "role": "user",
            "content": [
                {"type": "text", "text": prompt},
                {"type": "image_url", "image_url": {"url": image_uri}}
            ]
        }
        try:
            response = self.client.chat.completions.create(model=self.model, messages=[message], max_tokens=512)
            json_match = re.search(r'\{.*\}', response.choices[0].message.content, re.DOTALL)
            return json.loads(json_match.group(0)) if json_match else {}
        except Exception as e:
            print(f"❌ VLM analysis failed: {e}")
            return {}

# --- Tool 4: Explanation Synthesizer ---
class ExplanationSynthesizer:
    """
    Takes the VLM's answer and contextual data to generate a helpful explanation, using the compendium.
    """
    def __init__(self, client: OpenAI):
        self.client = client

    def synthesize(self, vlm_analysis: dict, original_question: dict, compendium: dict) -> str:
        prompt = f"""
        You are a helpful science tutor. Explain the answer using the provided system compendium and VLM analysis.
        The compendium describes the system's specialized tools. Use it as context.

        **System Knowledge Compendium:**
        {json.dumps(compendium.get('Textual_Compendium', {}), indent=2)}

        **Question:**
        {original_question['question']}

        **Choices:**
        {json.dumps(original_question['choices'])}

        **Analysis Result from VLM:**
        {json.dumps(vlm_analysis)}

        **Contextual Lecture:**
        {original_question['lecture']}

        Combine this information into a clear explanation. Start with the correct answer, then explain the reasoning, referencing the system's analytical capabilities where relevant.
        """
        message = {"role": "user", "content": prompt}
        try:
            response = self.client.chat.completions.create(model=MODEL, messages=[message], max_tokens=1024)
            return response.choices[0].message.content
        except Exception:
            return "Error generating explanation."

# --- Main Controller: The Orchestrator ---
class Orchestrator:
    """
    Manages the entire workflow, incorporating the compendium.
    """
    def __init__(self, api_key: str, api_base: str):
        print("\nOrchestrator is online. Initializing all system tools...")
        self.client = OpenAI(api_key=api_key, base_url=api_base)
        self.preprocessor = ImagePreprocessor()
        self.vlm_engine = VLMAnalysisEngine(self.client)
        self.synthesizer = ExplanationSynthesizer(self.client)
        print("All tools are ready. System is operational.")

    def run(self, data_item: dict, compendium: dict) -> tuple[dict, str]:
        """
        Executes the full pipeline and returns the analysis and explanation.
        """
        print("\n" + "="*50)
        print(f"Executing Workflow for QID: {data_item.get('qid', 'N/A')}")
        print("="*50)

        image_input, question, choices = data_item.get("image"), data_item.get("question"), data_item.get("choices")
        if not all([image_input, question, choices]):
            return {}, "Error: Data item is missing key fields."

        # Step 1: Preprocess Image
        image_data_uri = self.preprocessor.process(image_input)
        if not image_data_uri:
            return {}, "Workflow halted: Image preprocessing failed."

        # Step 2: Get VLM Analysis
        vlm_analysis = self.vlm_engine.analyze(image_data_uri, question, choices)
        if not vlm_analysis or 'answer_index' not in vlm_analysis:
            return {}, "Workflow halted: VLM analysis failed or returned invalid format."
        print(f"[Orchestrator] VLM Analysis Received: {vlm_analysis}")

        # Step 3: Synthesize Final Explanation using the Compendium
        final_explanation = self.synthesizer.synthesize(vlm_analysis, data_item, compendium)
        if not final_explanation:
            return vlm_analysis, "Workflow halted: Explanation synthesis failed."

        return vlm_analysis, final_explanation

if __name__ == "__main__":
    # *** IMPORTANT: PASTE YOUR API KEY HERE ***
    API_KEY = "secret_adaf_ff7e3e29179b4296b5b14cac2045c5f7.KxTTtYnoTgCClYtxUWZEyncRrvoAqanA"
    
    # --- Setup ---
    client = OpenAI(api_key=API_KEY, base_url=API_BASE)
    
    # --- Load Dataset ---
    print("\nLoading ScienceQA dataset from Hugging Face...")
    try:
        ds = load_dataset("derek-thomas/ScienceQA", split='test[:550]')
        print(f"Dataset loaded successfully with {len(ds)} entries.")
    except Exception as e:
        print(f"Failed to load dataset. Error: {e}")
        sys.exit(1)

    # --- Stage 1: Generate and Store a Single Compendium ---
    COMPENDIUM_FILENAME = "compendium.json"
    compendium_data = [item for item in ds.select(range(500)) if item.get('image')]
    compendium_generator = CompendiumGenerator(client)
    
    print("\n--- Generating a single, consolidated compendium ---")
    system_compendium = compendium_generator.generate(compendium_data)

    if system_compendium:
        try:
            with open(COMPENDIUM_FILENAME, 'w') as f:
                json.dump(system_compendium, f, indent=4)
            print(f"✅ Successfully saved compendium to '{COMPENDIUM_FILENAME}'")
        except IOError as e:
            print(f"❌ Error writing to file '{COMPENDIUM_FILENAME}': {e}")
            system_compendium = None # Ensure we don't proceed with a failed save
    else:
        print("⚠️ Failed to generate the compendium.")

    if not system_compendium:
        print("\nCritical Error: Could not generate system compendium. Aborting.")
        sys.exit(1)

    print("\n" + "="*60)
    print("GENERATED SYSTEM COMPENDIUM (for use in evaluation)")
    print("="*60)
    print(json.dumps(system_compendium, indent=2))
    print("="*60)


    # --- Stage 2: System Evaluation ---
    print("\nStarting intelligent system evaluation...")
    orchestrator = Orchestrator(api_key=API_KEY, api_base=API_BASE)
    
    test_data = [item for item in ds.select(range(500, len(ds))) if item.get('image')]
    
    correct_predictions = 0
    total_questions_processed = 0
    max_tests = 10
    
    start_time = time.time()

    for i, example in enumerate(test_data):
        if total_questions_processed >= max_tests:
            print(f"\nReached test limit of {max_tests} questions.")
            break
        
        total_questions_processed += 1
        print(f"\n>>> Processing Test Item #{i+1}/{max_tests} <<<")
        
        vlm_analysis, final_explanation = orchestrator.run(data_item=example, compendium=system_compendium)

        if vlm_analysis and 'answer_index' in vlm_analysis:
            print("\n--- VLM Structured Answer ---")
            print(json.dumps(vlm_analysis, indent=2))
            print("\n--- Final Explanation for Student ---")
            print(final_explanation)

            predicted_index = vlm_analysis['answer_index']
            ground_truth_index = example['answer']
            
            print(f"\n[Evaluation] Predicted Answer Index: {predicted_index}")
            print(f"[Evaluation] Ground Truth Index:     {ground_truth_index}")
            
            if predicted_index == ground_truth_index:
                correct_predictions += 1
                print("[Evaluation] Result: CORRECT ✔️")
            else:
                print("[Evaluation] Result: INCORRECT ❌")
        else:
            print("[Evaluation] Could not process item, skipping evaluation.")

    end_time = time.time()

    # --- Final Report ---
    print("\n" + "="*50)
    print("SYSTEM EVALUATION COMPLETE")
    print("="*50)
    
    total_time_taken = end_time - start_time
    accuracy = (correct_predictions / total_questions_processed * 100) if total_questions_processed > 0 else 0
    
    print(f"Total Questions Processed: {total_questions_processed}")
    print(f"Total Correct Predictions: {correct_predictions}")
    print(f"Accuracy: {accuracy:.2f}%")
    print(f"Total Time Taken: {total_time_taken:.2f} seconds")
    print("="*50)
